name: Dev Docker Multi-arch Image CI & CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Running Compile Nuxt3 Multi-arch Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kamera
        uses: actions/checkout@v4
      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Build Nuxt 3
        run: pnpm run build
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: set_up_buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push dev
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kamera:dev
